//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team09LogicU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.DeptStaffs = new HashSet<DeptStaff>();
        }
    
        public string deptID { get; set; }
        public string deptName { get; set; }
        public string contactStaffID { get; set; }
        public string headStaffID { get; set; }
        public string repStaffID { get; set; }
        public string collectionPointID { get; set; }
        public string fax { get; set; }
        public string phone { get; set; }
    
        public virtual CollectionPoint CollectionPoint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeptStaff> DeptStaffs { get; set; }
    }
}
