//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team09LogicU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisitionItem
    {
        public int reqItemID { get; set; }
        public int requisitionID { get; set; }
        public string itemID { get; set; }
        public int requisitionQty { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Requisition Requisition { get; set; }
    }
}
