//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team09LogicU.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SA45_Team09_LogicUEntities : DbContext
    {
        public SA45_Team09_LogicUEntities()
            : base("name=SA45_Team09_LogicUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdjustmentVoucher> AdjustmentVouchers { get; set; }
        public virtual DbSet<AdjustmentVoucherItem> AdjustmentVoucherItems { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CollectionPoint> CollectionPoints { get; set; }
        public virtual DbSet<Delegate> Delegates { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DeptNotification> DeptNotifications { get; set; }
        public virtual DbSet<DeptStaff> DeptStaffs { get; set; }
        public virtual DbSet<Disbursement> Disbursements { get; set; }
        public virtual DbSet<DisbursementItem> DisbursementItems { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Outstanding> Outstandings { get; set; }
        public virtual DbSet<OutstandingItem> OutstandingItems { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<PurchaseOrderItem> PurchaseOrderItems { get; set; }
        public virtual DbSet<Requisition> Requisitions { get; set; }
        public virtual DbSet<RequisitionItem> RequisitionItems { get; set; }
        public virtual DbSet<Retrieval> Retrievals { get; set; }
        public virtual DbSet<RetrievalItem> RetrievalItems { get; set; }
        public virtual DbSet<StockCard> StockCards { get; set; }
        public virtual DbSet<StoreNotification> StoreNotifications { get; set; }
        public virtual DbSet<StoreStaff> StoreStaffs { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<SupplierItem> SupplierItems { get; set; }
    }
}
