//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team09LogicU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreNotification
    {
        public int notificationID { get; set; }
        public string storeStaffID { get; set; }
        public string message { get; set; }
        public System.DateTime date { get; set; }
        public string status { get; set; }
    }
}
