<%@ Page Title="" Language="C#" MasterPageFile="~/Pages/DepartmentHead.Master" AutoEventWireup="true" CodeBehind="DH_PendingRequisitionDetail.aspx.cs" Inherits="Team09LogicU.Pages.DH_PendingRequisitionDetail" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
   PendingRequisitionDetail
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">

    <form id ="form1" runat="server">
        
           
                <div class="row"> 
                    <div class="col-lg-12">
                        <div class="card">
                             <div class=" container" style="margin-left:-10px">
                             <div  class=" col-lg-3" style="margin-top:20px">
                                 <asp:Label ID="Label_ReqID" CssClass="h4" runat="server" Text="Requisition ID: "></asp:Label>
                                 <asp:Label ID="lblReqID" CssClass="h5" runat="server"></asp:Label> 
                                 </div><div  class=" col-lg-3" style="margin-left:-60px ; margin-top:20px">
                             
                                 <asp:Label ID="Label_ReqDate" CssClass="h4" runat="server" Text="Request Date: "></asp:Label>
                                 <asp:Label ID="lblDate" CssClass="h5" runat="server"></asp:Label> 
                              
                               </div><div class=" col-lg-4" style="margin-bottom:30px ; margin-top:20px">
                                  <asp:Label ID="Label_Name" CssClass="h4" runat="server" Text="Request Staff: "></asp:Label>  
                                  <asp:Label ID="lblStaff" CssClass="h5" runat="server"></asp:Label></div>
                                 <div class=" col-lg-10" style="margin-bottom:30px ">
                                  <asp:GridView ID="GridView_detailList" runat="server" CssClass="table table-hover table-striped" HeaderStyle-CssClass=" content text-uppercase  " EmptyDataText="There are no record!" EditRowStyle-CssClass="btn btn-warning btn-fill fa fa-edit" AutoGenerateDeleteButton="False" AutoGenerateEditButton="False" AutoGenerateSelectButton="False" CellPadding="4" ForeColor="#333333" GridLines="None" >
                                      <AlternatingRowStyle BackColor="White" />
                                </asp:GridView> <asp:Label ID="label4" runat="server" CssClass="category" Text=" Remarks:"></asp:Label>
                                     <p></p>
                                 <asp:TextBox ID="TextBox_Remarks" style="resize:none" CssClass="form-control" runat="server" TextMode="MultiLine" ></asp:TextBox>
                               </div>  </div>
                             <div  class=" col-lg-10" style="margin-top:20px">
                              
                             <asp:Button ID="Btn_Approve"  runat="server" Text="Approve" CssClass="btn btn-primary btn-fill btn-wd " OnClick="Btn_Approve_Click" /> <%--此处点击事件--%>
                            <asp:Button ID="Btn_Reject"  runat="server" Text="Reject"  CssClass="btn btn-danger btn-fill btn-wd " OnClick="Btn_Reject_Click" /><%--此处点击事件--%>
  </div>  </div>
     </div>
  </div>
  
        </form>

</asp:Content>
