<%@ Page Title="" Language="C#" MasterPageFile="~/Pages/DepartmentHead.Master" AutoEventWireup="true" CodeBehind="DH_PendingRequisitionDetail.aspx.cs" Inherits="Team09LogicU.Pages.DH_PendingRequisitionDetail" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
   PendingRequisitionDetail
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">

    <form id ="form1" runat="server">
         <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-9">
                        <div class="card">
                            <div class="header">
                             <p class="category">
                                 <asp:Label ID="Label_ReqID" runat="server" Text="Requisition ID: "></asp:Label>
                                 <asp:Label ID="lblReqID" runat="server"></asp:Label> 

                             <p class="category">
                                 <asp:Label ID="Label_ReqDate" runat="server" Text="Request Date: "></asp:Label>
                                 <asp:Label ID="lblDate" runat="server"></asp:Label> 
                              
                                <p class="category"> 
                                  <asp:Label ID="Label_Name" runat="server" Text="Request Staff: "></asp:Label>  
                                  <asp:Label ID="lblStaff" runat="server"></asp:Label>
         

                            </div> 
                            <p>
                        

                                  <asp:GridView ID="GridView_detailList" runat="server" CssClass="table bootstrap-table table-hover table-striped" HeaderStyle-CssClass=" content text-uppercase  " EmptyDataText="There are no record!" EditRowStyle-CssClass="btn btn-warning btn-fill fa fa-edit" AutoGenerateDeleteButton="False" AutoGenerateEditButton="False" AutoGenerateSelectButton="False" CellPadding="4" ForeColor="#333333" GridLines="None" >


                                     <AlternatingRowStyle BackColor="White" />
                                </asp:GridView>
                            </p>

                             <p class="category">   
                                 <div  class="col-md-1">
                                    <asp:Label ID="label4" runat="server" Text=" Remarks:"></asp:Label>
                                 </div>
                                 <div  class="col-md-6">
                                 <asp:TextBox ID="TextBox_Remarks" style="resize:none" runat="server" Height="59px" TextMode="MultiLine" Width="192px"></asp:TextBox>

                                 </div>
                                 </p> 
                     </div>         
        </div>
     </div>
   </div>
 </div>                         
                          
  
    <asp:Button ID="Btn_Approve"  runat="server" Text="Approve" CssClass="btn btn-primary btn-fill btn-wd " OnClick="Btn_Approve_Click" /> <%--此处点击事件--%>
    <asp:Button ID="Btn_Reject"  runat="server" Text="Reject"  CssClass="btn btn-danger btn-fill btn-wd " OnClick="Btn_Reject_Click" /><%--此处点击事件--%>

  
        </form>

</asp:Content>
