<%@ Page Title="" Language="C#" MasterPageFile="~/Pages/DepartmentHead.Master" AutoEventWireup="true" CodeBehind="DH_RequisitionHistoryDetail.aspx.cs" Inherits="Team09LogicU.Pages.DH_RequisitionHistoryDetail" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    Requisition History Detail
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">

   
  <div class="row">
         <div class="col-lg-12">
        <div class="card">
                <div class=" container">
                            <div  class=" col-lg-3" style="margin-top:20px">
                                    <asp:Label ID="Label_ReqID" runat="server" Text="Requisition ID: " CssClass="category"></asp:Label>
                                    <asp:Label ID="lblReqID" runat="server" CssClass="h6"></asp:Label>
                                </div>
                               <div  class=" col-lg-3" style="margin-top:20px">
                                    <asp:Label ID="Label_ReqDate" runat="server" Text="Request Date: " CssClass="category"></asp:Label>
                                    <asp:Label ID="lblDate" runat="server" CssClass="h6"></asp:Label>
                                     </div>
                               <div  class=" col-lg-3" style="margin-top:20px">
                              
                                    <asp:Label ID="Label_Name" runat="server" Text="Request Staff: " CssClass="category"></asp:Label>
                                    <asp:Label ID="lblStaff" runat="server" CssClass="h6"></asp:Label>
                                     </div>
                                <div class="col-lg-10" style="margin-top:20px">
                                <asp:GridView ID="GridView_detailList" runat="server" AllowPaging="true" OnPageIndexChanging="GridView_detailList_PageIndexChanging" OnRowCommand="GridView_detailList_RowCommand" CssClass="table table-hover table-striped" HeaderStyle-CssClass=" content text-uppercase  " EmptyDataText="There are no record" EditRowStyle-CssClass="btn btn-warning btn-fill fa fa-edit" AutoGenerateDeleteButton="False" AutoGenerateEditButton="False" AutoGenerateSelectButton="False" CellPadding="4" ForeColor="#333333" GridLines="None">

                                     <PagerTemplate>
                                <br />
                                <div class="col-lg-12 ">
                                    <div class="col-lg-3 " style="width:18%">
                                     <asp:Label ID="lblPage" runat="server" Text='<%# "Page:" + (((GridView)Container.NamingContainer).PageIndex + 1)  + "/" + (((GridView)Container.NamingContainer).PageCount)  %> '></asp:Label>
                                     <asp:LinkButton ID="lbnFirst" runat="Server" Text="First" CssClass="btn btn-xs btn-default" Enabled='<%# ((GridView)Container.NamingContainer).PageIndex != 0 %>' CommandName="Page" CommandArgument="First"></asp:LinkButton>
                                    <asp:LinkButton ID="lbnPrev" runat="server" Text="<<" CssClass="btn btn-xs btn-default" Enabled='<%# ((GridView)Container.NamingContainer).PageIndex != 0 %>' CommandName="Page" CommandArgument="Prev"></asp:LinkButton>
                                   </div><div class="col-lg-1" style="Width:10%"><asp:TextBox runat="server" CssClass="form-control text-center "  ID="inPageNum" Text='<%# ((GridView)Container.NamingContainer).PageIndex +1 %>'></asp:TextBox>
                                    </div><div class="col-lg-3 ">
                                       <asp:LinkButton ID="lbnNext" runat="Server" Text=">>" CssClass="btn btn-xs btn-default" Enabled='<%# ((GridView)Container.NamingContainer).PageIndex != (((GridView)Container.NamingContainer).PageCount - 1) %>' CommandName="Page" CommandArgument="Next"></asp:LinkButton>
                                   <asp:LinkButton ID="lbnLast" runat="Server" Text="Last" CssClass="btn btn-xs btn-default" Enabled='<%# ((GridView)Container.NamingContainer).PageIndex != (((GridView)Container.NamingContainer).PageCount - 1) %>' CommandName="Page" CommandArgument="Last"></asp:LinkButton>
                                     <asp:Button ID="Button1" CommandName="go" CssClass="btn btn-xs btn-default" Text="GO" runat="server" />
                                    </div></div>
                                    
                            </PagerTemplate>
                                    <AlternatingRowStyle BackColor="White" />
                                </asp:GridView>
                                      </div>
                                     <div class="col-lg-10" style="margin-top:20px;margin-bottom:20px">
                                     <asp:Label ID="Label_Remark" runat="server" Text="Remark: " CssClass="category"></asp:Label><br>
                                    <asp:Label ID="lblRemark" runat="server" CssClass="h5"></asp:Label>
                            </div>
                     

                        </div>
            <div class="col-lg-10" style="margin-top:20px;margin-bottom:20px">
                           <div class="col-lg-2">
                     <asp:Button ID="Btn_Back"  runat="server" Text="Back"  CssClass="btn btn-default btn-fill btn-wd " OnClick="Btn_Back_Click" />
                               </div>
                         </div>
                    </div>
                </div>
            </div>
      

    


</asp:Content>
