<%@ Page Title="" Language="C#" MasterPageFile="~/Pages/DepartmentHead.Master" AutoEventWireup="true" CodeBehind="DH_RequisitionHistoryDetail.aspx.cs" Inherits="Team09LogicU.Pages.DH_RequisitionHistoryDetail" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    Requisition History Detail
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">

     <form id ="form1" runat="server">
         <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-9">
                        <div class="card">
                            <div class="header">
                             <p class="category">
                                  <asp:Label ID="label1" runat="server" Text="Request Date: "></asp:Label>
                                   <asp:Label ID="label_RequestedDated" runat="server" ></asp:Label>  </p> 
                              <p class="category">   
                                  <asp:Label ID="label2" runat="server" Text=" Requested By:"></asp:Label>
                                    <asp:Label ID="label_Employee" runat="server" ></asp:Label> </p> <%--此处传值--%>
         
                            
                            </div> 
                            <p>
                        

                                  <asp:GridView ID="GridView1" runat="server" CssClass="table bootstrap-table table-hover table-striped" HeaderStyle-CssClass=" content text-uppercase  "  AllowPaging="True" EditRowStyle-CssClass="btn btn-warning btn-fill fa fa-edit" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" CellPadding="4" ForeColor="#333333" GridLines="None" >


                                     <AlternatingRowStyle BackColor="White" />
                                </asp:GridView>

                            </p>
                     </div>
         
        </div>
     </div>
   </div>
 </div>                         
                          
  
        </form>


</asp:Content>
