<%@ Page Title="" Language="C#" MasterPageFile="~/Pages/StoreClerk.Master" AutoEventWireup="true" CodeBehind="SC_Inv_StockCardDetail.aspx.cs" Inherits="Team09LogicU.Pages.SC_Inv_StockCardDetail" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    Stock Card
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">

    <form id ="form1" runat="server">
         <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-9">
                        <div class="card">
                            <div class="header">
                             <p class="category">
                                  <asp:Label ID="label1" runat="server" Text="Item Code: "></asp:Label>
                                   <asp:Label ID="label_itemcode" runat="server" ></asp:Label>  </p> 
                              <p class="category">   
                                  <asp:Label ID="label2" runat="server" Text=" Unit of mesaure:"></asp:Label>
                                    <asp:Label ID="label_measure" runat="server" ></asp:Label> </p> 
         
                              <p class="category">    
                                  <asp:Label ID="Label3" runat="server" Text="Supplier1: "></asp:Label>
                                 <asp:Label ID="label_Supplier1" runat="server" ></asp:Label></p>   
                                 <p class="category">    
                                  <asp:Label ID="Label4" runat="server" Text="Supplier2: "></asp:Label>
                                 <asp:Label ID="label_Supplier2" runat="server" ></asp:Label></p> 
                                 <p class="category">    
                                  <asp:Label ID="Label6" runat="server" Text="Supplier3: "></asp:Label>
                                 <asp:Label ID="label_Supplier3" runat="server"></asp:Label></p> 


                            </div> 
                            <p>
                       
                                
                                     <asp:GridView ID="GridView1" runat="server"   CssClass="table bootstrap-table table-hover table-striped" HeaderStyle-CssClass=" content text-uppercase  "  AllowPaging="True" EditRowStyle-CssClass="btn btn-warning btn-fill fa fa-edit" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" CellPadding="4" ForeColor="#333333" GridLines="None"></asp:GridView>   
                                      <AlternatingRowStyle BackColor="White" />


                            </p>
                     </div>
         
        </div>
     </div>
   </div>
 </div>                         
                          
    <asp:Button ID="Btn_Back"  runat="server"  Text="Back"  CssClass="btn btn-default  btn-fill btn-wd"   />
        </form>
</asp:Content>
